/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Uinterface;
import CBusiness.Car;

/**
 *
 * @author DivyaThanigaiArasu
 */
public class CarJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CarJFrame
     */
    private Car car;
    public CarJFrame() {
        initComponents();
        car = new Car();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlCarJPanel = new javax.swing.JPanel();
        createCarBtn = new javax.swing.JButton();
        viewCarBtn = new javax.swing.JButton();
        displayCarJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createCarBtn.setText("Create");
        createCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCarBtnActionPerformed(evt);
            }
        });

        viewCarBtn.setText("View");
        viewCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlCarJPanelLayout = new javax.swing.GroupLayout(controlCarJPanel);
        controlCarJPanel.setLayout(controlCarJPanelLayout);
        controlCarJPanelLayout.setHorizontalGroup(
            controlCarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlCarJPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(controlCarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewCarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createCarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        controlCarJPanelLayout.setVerticalGroup(
            controlCarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlCarJPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(createCarBtn)
                .addGap(35, 35, 35)
                .addComponent(viewCarBtn)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(controlCarJPanel);

        javax.swing.GroupLayout displayCarJPanelLayout = new javax.swing.GroupLayout(displayCarJPanel);
        displayCarJPanel.setLayout(displayCarJPanelLayout);
        displayCarJPanelLayout.setHorizontalGroup(
            displayCarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );
        displayCarJPanelLayout.setVerticalGroup(
            displayCarJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(displayCarJPanel);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCarBtnActionPerformed
        CreateCarJPanel createCarPanel = new CreateCarJPanel(car);
        splitPane.setRightComponent(createCarPanel);
    }//GEN-LAST:event_createCarBtnActionPerformed

    private void viewCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCarBtnActionPerformed
        ViewCarJPanel viewCarPanel = new ViewCarJPanel(car);
        splitPane.setRightComponent(viewCarPanel);
    }//GEN-LAST:event_viewCarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlCarJPanel;
    private javax.swing.JButton createCarBtn;
    private javax.swing.JPanel displayCarJPanel;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JButton viewCarBtn;
    // End of variables declaration//GEN-END:variables
}
