/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.FleetDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author DivyaThanigaiArasu
 */
public class FleetMngWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private FleetDirectory fleetDirectory;

    /**
     * Creates new form FleetMngWorkAreaJPanel
     */
    FleetMngWorkAreaJPanel(JPanel userProcessContainer, FleetDirectory fleetDirectory) {
     initComponents();
     this.userProcessContainer = userProcessContainer;
     this.fleetDirectory = fleetDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateCar = new javax.swing.JButton();
        btnMngFleet = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));

        btnCreateCar.setText("Add New Car");
        btnCreateCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCarActionPerformed(evt);
            }
        });

        btnMngFleet.setText("Manage Fleet");
        btnMngFleet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngFleetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMngFleet, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateCar, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(503, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnCreateCar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnMngFleet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCarActionPerformed
        // TODO add your handling code here:
        CreateCarJPanel panel = new CreateCarJPanel(userProcessContainer, fleetDirectory);
        userProcessContainer.add("CreateCarJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateCarActionPerformed

    private void btnMngFleetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngFleetActionPerformed
        // TODO add your handling code here:
        MngFleetJPanel panel = new MngFleetJPanel(userProcessContainer, fleetDirectory);
        userProcessContainer.add("MngFleetJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngFleetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCar;
    private javax.swing.JButton btnMngFleet;
    // End of variables declaration//GEN-END:variables
}
